### ISSUE TITLE
Add navigation quicklink for portal/headnode

### ISSUE THREAD

**Issue by aaaaalbert** [EdgeNet-project/edgenet-project.github.io#11]
User @boldt suggests:
> Add a quick-link to the portal on http://edge-net.org/ navigation. It just took me a while to find it again.

Great idea! Let's do this!

**Comment by aaaaalbert** [comment]
Fixed, thanks @boldt for the suggestion!

The Portal links to the headnode quite prominently, but let me know if you think another quicklink is warranted.

**Comment by boldt** [comment]
LGTM
