### ISSUE TITLE
Cert has apparently expired

### ISSUE THREAD

**Issue by rickmcgeer** [EdgeNet-project/edgenet-project.github.io#4]
I'm seeing this when I try to access edge-net.org, so it appears our cert has expired
![screen shot 2018-07-29 at 11 38 44 am](https://user-images.githubusercontent.com/656259/43369663-b94ed948-9326-11e8-989d-345cae93941c.png)

**Comment by aaaaalbert** [comment]
Cannot replicate. If somebody fixed this, please comment on this issue.

**Comment by aaaaalbert** [comment]
The error message complained about a *name mismatch* actually. Right now, we use a Let's Encrypt cert on the portal, so the issue no longer exists.

Closing.
